import { contentAnalysisPrompt } from "@/src/ai/prompts/content/content-analysis.prompt";
import { emotionAnalysisPrompt } from "@/src/ai/prompts/content/emotion-analysis.prompt";
import { hookAnalysisPrompt } from "@/src/ai/prompts/content/hook-analysis.prompt";
import { marketingContentPrompt } from "@/src/ai/prompts/content/marketing-content.prompt";
import { optimizationPrompt } from "@/src/ai/prompts/content/optimization.prompt";
import { scriptGenerationPrompt } from "@/src/ai/prompts/content/script-generation.prompt";
import { structureAnalysisPrompt } from "@/src/ai/prompts/content/structure-analysis.prompt";
import { AnalysisSchema, EmotionSchema, GeneratedScriptSchema, HookSchema, MarketingSchema, OptimizationSchema, StructureNodeSchema, type Analysis, type Emotion, type GeneratedScript, type Hook, type Optimization, type StructureNode } from "@/src/ai/schemas/content-analysis.schema";
import { StructuredGenerationService } from "@/src/ai/structured/structured-generation.service";
import type { WorkflowDefinition } from "../workflow-types";

export const fullContentAnalysisWorkflow: WorkflowDefinition = {
  type: "FULL_CONTENT_ANALYSIS",
  steps: [
    { key: "content-analysis", stepType: "STRUCTURED_OUTPUT", title: "内容分析", sequence: 1, execute: async (context) => new StructuredGenerationService(context.provider, context.recordUsage).generate(contentAnalysisPrompt, { inputType: context.input.inputType, content: context.input.content }) },
    { key: "hook-analysis", stepType: "STRUCTURED_OUTPUT", title: "钩子分析", sequence: 2, execute: async (context, input) => { const outputs = input as Record<string, unknown>; const analysis: Analysis = AnalysisSchema.parse(outputs["content-analysis"]); return new StructuredGenerationService(context.provider, context.recordUsage).generate(hookAnalysisPrompt, { inputType: context.input.inputType, content: context.input.content, analysis }); } },
    { key: "structure-analysis", stepType: "STRUCTURED_OUTPUT", title: "结构分析", sequence: 3, execute: async (context, input) => { const outputs = input as Record<string, unknown>; const analysis: Analysis = AnalysisSchema.parse(outputs["content-analysis"]); const hook: Hook = HookSchema.parse(outputs["hook-analysis"]); return new StructuredGenerationService(context.provider, context.recordUsage).generate(structureAnalysisPrompt, { inputType: context.input.inputType, content: context.input.content, analysis, hook }); } },
    { key: "emotion-analysis", stepType: "STRUCTURED_OUTPUT", title: "情绪分析", sequence: 4, execute: async (context, input) => { const outputs = input as Record<string, unknown>; const analysis: Analysis = AnalysisSchema.parse(outputs["content-analysis"]); const structure: StructureNode[] = StructureNodeSchema.array().max(20).parse(outputs["structure-analysis"]); return new StructuredGenerationService(context.provider, context.recordUsage).generate(emotionAnalysisPrompt, { inputType: context.input.inputType, content: context.input.content, analysis, structure }); } },
    { key: "optimization", stepType: "STRUCTURED_OUTPUT", title: "内容优化", sequence: 5, execute: async (context, input) => { const outputs = input as Record<string, unknown>; const analysis: Analysis = AnalysisSchema.parse(outputs["content-analysis"]); const hook: Hook = HookSchema.parse(outputs["hook-analysis"]); const structure = StructureNodeSchema.array().max(20).parse(outputs["structure-analysis"]); const emotion: Emotion = EmotionSchema.parse(outputs["emotion-analysis"]); return new StructuredGenerationService(context.provider, context.recordUsage).generate(optimizationPrompt, { content: context.input.content, analysis, hook, structure, emotion }); } },
    { key: "script-generation", stepType: "STRUCTURED_OUTPUT", title: "脚本生成", sequence: 6, execute: async (context, input) => { const outputs = input as Record<string, unknown>; const analysis: Analysis = AnalysisSchema.parse(outputs["content-analysis"]); const hook: Hook = HookSchema.parse(outputs["hook-analysis"]); const structure = StructureNodeSchema.array().max(20).parse(outputs["structure-analysis"]); const emotion: Emotion = EmotionSchema.parse(outputs["emotion-analysis"]); const optimization: Optimization = OptimizationSchema.parse(outputs.optimization); return new StructuredGenerationService(context.provider, context.recordUsage).generate(scriptGenerationPrompt, { content: context.input.content, analysis, hook, structure, emotion, optimization }); } },
    { key: "marketing-content", stepType: "STRUCTURED_OUTPUT", title: "营销内容", sequence: 7, execute: async (context, input) => { const outputs = input as Record<string, unknown>; const analysis: Analysis = AnalysisSchema.parse(outputs["content-analysis"]); const generatedScript: GeneratedScript = GeneratedScriptSchema.parse(outputs["script-generation"]); return new StructuredGenerationService(context.provider, context.recordUsage).generate(marketingContentPrompt, { content: context.input.content, analysis, generatedScript }); } },
  ],
};

export const fullContentOutputSchemas = { analysis: AnalysisSchema, hook: HookSchema, structure: StructureNodeSchema.array().max(20), emotion: EmotionSchema, optimization: OptimizationSchema, generatedScript: GeneratedScriptSchema, marketing: MarketingSchema };
